### ISSUE TITLE
Review Carto layers workflow

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#114]
See https://github.com/Vizzuality/TRASE-frontend/issues/421

Running getContextMaps.sh will affect CARTO context layers on all instances of the project, including production. This caused bugs in production and needs to be addressed.

**Comment by nerik** [comment]
This should actually been already fixed. Latest iteration of the script will instantiate a new named map for each context layer, rather than updating it. 
One thing to look after: CARTO has a max of 4000 named maps, so it might be an issue in a few years, if we are still using CARTO, if computers still exist, and if we haven't been replaced by tardigrades.
