### ISSUE TITLE
Map: Expand bivariate maps from 9 to 16 buckets

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#179]
https://basecamp.com/1756858/projects/12498794/todos/320705520
https://basecamp.com/1756858/projects/12498794/todos/322939121
https://github.com/Vizzuality/trase/issues/104

- New admin interface should allow manually changing these values
- The tool should pre-fill the yellow table bucket values with a sensible default (calculate max and min, and separate range into equal intervals).
- Some layers will have un-standard number of buckets, need to take that into account

Test
- Bi-dimension choropleth show up a 4x4 grid of values, instead of current 3x3
- Single dimension choropleth remains as-is
- Test that "0" and "na" values remain as they currently are.

**Comment by agnessa** [comment]
The current bucket_5 will be an array of multiple length which represents the single dimension; it might have more than 4 values as it currently has.

The current bucket_3 is used when 2 dimensions applied and it has 2 values; it needs to be changed to allow 3 values.

**Comment by tiagojsag** [comment]
on bucket_3, you may actually enforce it to have an array of 3 numbers

**Comment by agnessa** [comment]
I propose to rename them `univariate_buckets` and `bivariate_buckets`

**Comment by tiagojsag** [comment]
how about something simpler, like single_layer_buckets and dual_layer_buckets?

**Comment by agnessa** [comment]
well I do like my Latin, but if you insist ;) sure, as long as the intention of the column is clear.

**Comment by tiagojsag** [comment]
I dont insist, just seems easier to read, especially for non-natives. But pick your favorite

**Comment by agnessa** [comment]
About this requirement to pre-fill with sensible values. I think we discussed that at some point not to make the default values part of the importing process for now, relying on validation endpoint + admin tool instead to sort out post-import configuration. So just double checking whether this is about setting the default value as part of post-import process (which I think is more complex than it seems, because I'm not sure how we can reliably decide whether or not e.g. a new map attribute should be created), or perhaps when someone goes to the admin tool, starts adding a new map attribute and the buckets come up populated in the form?

Another question, how do I rescale the current values for bucket_3?
