### ISSUE TITLE
New endpoint(s) for world map page

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#285]
https://projects.invisionapp.com/d/main#/console/13083466/273638941/preview

Description:
- Need an endpoint to serve top destination countries per context
- Need an endpoint to serve top exporters per context (may be same endpoint, may be different)
- Need to figure out a place to save which flows column corresponds to this (context?)
- Idea to explore: an endpoint that expects a context id and a node type id/column id/(what do we call these these days?) and returns a top X + others of that metric for that context, always per volume of traded commodity

**Comment by agnessa** [comment]
https://github.com/Vizzuality/trase/pull/289

**Comment by agnessa** [comment]
Not sure what is needed in terms of: "Need to figure out a place to save which flows column corresponds to this (context?)" - is this about "how will the front-end know which node type id to request"? We could avoid that problem by passing the node type name rather than id, or otherwise I guess we'd could add this information to the /contexts call, e.g. `top_countries_column_id`, `top_exporters_column_id`.

**Comment by tiagojsag** [comment]
So two questions here:
- Who keeps info on what columns should be requested, the frontend or the backend?
Storing this on the database feels more elegant and future-proof, but also feels a bit overkill.

- How should the frontend ask the backend for those columns? name or id?
If we store this in the DB, id id id id. Name comparison is evil :P

**Comment by agnessa** [comment]
OK; I guess what we should try to do is keep it similar to how the flows call is parametrised, although it does feel like overkill to add a new table for that.
