### ISSUE TITLE
Update let's encrypt config

### ISSUE THREAD

**Issue by sorodrigo** [Vizzuality/trase#422]
We need to update let's encrypt config to respawn the server everytime the certificate gets renewed. More info [here](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04).

**Comment by agnessa** [comment]
I followed the [instructions](https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx) to install certbot from package, specifically:

```
$ sudo apt-get update
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository universe
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install certbot python-certbot-nginx
```

I then updated the crontabs in a way that hopefully makes sure nginx is reloaded:

`0 0 * * * env PATH="$PATH:/usr/sbin" certbot renew --nginx --no-self-upgrade --quiet`

I also temporarily used the `--force-renewal` option on all servers to make sure this works (but removed that option from crontabs since).

You can check the ceritificate expiry using:
`sudo certbot --no-self-upgrade certificates`

Certificates are valid for 90 days. They attempt to renew after 60 days.
