### ISSUE TITLE
Issue with map zooming

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#516]
See https://basecamp.com/1756858/projects/12498794/todos/327056118

**Comment by tsubik** [comment]
So far I found a reliable way to reproduce that or something very similar (on staging), the fix is on its way.

1. Go to Map. Wait for things to load.
2. Using top menu go back to home page.
3. Go to Supply Chain.
4. Using the map click on Altamira.

![map-zoom-out](https://user-images.githubusercontent.com/1286444/41665899-6d454794-74a9-11e8-9ddd-395798e854b2.gif)
