### ISSUE TITLE
Create project domain documentation

### ISSUE THREAD

**Issue by agnessa** [Vizzuality/trase#717]
We need an introduction into the concepts in Trase. This is the proposed minimum table of contents:

Introduction to core concepts
- contexts
- nodes and types of nodes
- flows and flow paths
- inds, quants and quals
- node attributes and flow attributes
Core data vs configuration
- blue vs yellow tables
- description of currently available configuration options

**Comment by aabdaab** [comment]
I think this could be a good starting point. I would much benefit from docs about the topics above. Even things like we discussed in here #712, like:
What is a flow? What compounds make a flow, from that we can draw what are the limitations of a flow, i.. there can be only one country of destination in a single flow (single source as well then?)
Or, what you said in PT task: `It should never happen that 2 companies of same "type", i.e. 2 exporters, will appear at the same time in the path`.
We could start with a glossary of terms we use in a project on a daily basic (flow, path, context, ...) and basic use cases. I think from that it will start to grow because once we start listing the basics, more complex scenarios will come to mind (edge cases, implications on a different part of application, things like that).

**Comment by agnessa** [comment]
https://github.com/Vizzuality/trase/pull/909
