### ISSUE TITLE
Design review on the pdf version of the profile page

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#89]
@juancarlosalonso we need your design review here.

[ProfilePage-1511434076183.pdf](https://github.com/Vizzuality/trase/files/1498733/ProfilePage-1511434076183.pdf)

**Comment by nerik** [comment]
@tiagojsag The link you provided does not accurately picture the work done on this PR, as the PDF service points to staging (https://github.com/Vizzuality/trase/pull/74/files#diff-947fb4c8a3ec1a2de79330162f506085R43), which does not support the `print` parameter.

You need to deploy the `download-profile-page-as-pdf` branch somewhere in order to test this.

**Comment by tiagojsag** [comment]
did not know that. merged and deployed to staging. @juancarlosalonso @nerik let's review

**Comment by nerik** [comment]
Thanks @tiagojsag.

And this is the actor profile PDF:
[TRASE.-.Place.profile-1511855635492.pdf](https://github.com/Vizzuality/trase/files/1509208/TRASE.-.Place.profile-1511855635492.pdf)

@juancarlosalonso Don't bother commenting the obviously broken things.
@tiagojsag A lot of the layout breakage are due to a too small viewport, but I this has to be configured on the service.

**Comment by juancarlosalonso** [comment]
Main changes would be:
- [ ] Increase margins
- [ ] Remove the menu
- [ ] Avoid elements to break into two pages
- [ ] Change Map outlines to white

**Comment by tiagojsag** [comment]
@sorodrigo please review the list above and see if you have any questions.

**Comment by tiagojsag** [comment]
superseeded by https://github.com/Vizzuality/trase/issues/191
